providers = ["ruby"]
[phases.install]
cmds = ["bundle install"]
[phases.build]
cmds = ["bundle exec rake assets:precompile && bundle exec rake assets:clean && bundle exec rake db:migrate && bundle exec rake db:seed"]
[start]
cmd = "./bin/rails server"